export const Message ={
  success:"Thành công!",
  fail:"Thất bại",
  Error:"Lỗi!",
  systemError:"Lỗi hệ thống!",
  msgExist:"Đã tồn tại sản phẩm này rồi!",
  ADD_BOOK_SUCCESS: "Thêm sách thành công",
  ADD_BOOK_FAIL: "Thêm sách thất bại",
  DUPLICATE_BOOK_NAME: "Tên sách đã tồn tại",
  UPDATE_BOOK_SUCCESS: "Cập nhật sách thành công",
  UPDATE_BOOK_FAIL: "Cập nhật sách thất bại",
  DELETE_BOOK_SUCCESS: "Xóa sách thành công",
  DELETE_BOOK_FAIL: "Xóa sách thất bại",
  ADD_CATEGORY_SUCCESS: "Thêm Loại sách thành công",
  ADD_CATEGORY_FAIL: "Thêm loại sách thất bại",
  DUPLICATE_CATEGORY_NAME: "Tên thể loại đã tồn tại",
  UPDATE_CATEGORY_SUCCESS: "Cập nhật thể loại sách thành công",
  UPDATE_CATEGORY_FAIL: "Cập nhật thể loại sách thất bại",
  QUES_CONFIRM_EXIT_FORM: "Dữ liệu đang điền sẽ bị mất, bạn muốn rời khỏi trang này không?",
  DELETE_CATEGORY_SUCCESS: "Xóa thể loại sách thành công",
  DELETE_CATEGORY_FAIL: "Xóa thể loại sách thất bại",
  QUES_NOT_EXISTED_BOOK: "Không tìm thấy sách. Sách này có thể đã bị xóa trước đó, bạn muốn tải lại trang này không?",
  QUES_NOT_EXISTED_CATEGORY: "Không tìm thấy thể loại sách. Thể loại này có thể đã bị xóa trước đó, bạn muốn tải lại trang này không?",
  QUES_VIEW_BOOK_BY_CATEGORY: "Đang có sách thuộc thể loại này. Bạn muốn xem các sách thuộc thể loại này không?",
  QUES_AFTER_DELETE_BOOK_DETAIL: "Xóa sách thành công, bạn muốn về trang quản lý không?",
  QUES_NOT_EXISTED_BOOK_DETAIL: "Không tìm thấy sách. Sách này có thể đã bị xóa trước đó, bạn muốn về trang quản lý không?"
}